---
abstract: 'class-based HTML-centric templating system'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose::Util: 0
  Test::More: 0.88
  Test::Routine: 0
  Test::Routine::Util: 0
  autodie: 0
  perl: v5.10.0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Caribou
provides:
  Template::Caribou:
    file: lib/Template/Caribou.pm
    version: v0.2.2
  Template::Caribou::Files:
    file: lib/Template/Caribou/Files.pm
    version: v0.2.2
  Template::Caribou::Formatter:
    file: lib/Template/Caribou/Formatter.pm
    version: v0.2.2
  Template::Caribou::Formatter::Twig:
    file: lib/Template/Caribou/Formatter/Twig.pm
    version: v0.2.2
  Template::Caribou::Manual:
    file: lib/Template/Caribou/Manual.pod
    version: v0.2.2
  Template::Caribou::Tags:
    file: lib/Template/Caribou/Tags.pm
    version: v0.2.2
  Template::Caribou::Tags::Bootstrap:
    file: lib/Template/Caribou/Tags/Bootstrap.pm
    version: v0.2.2
  Template::Caribou::Tags::HTML:
    file: lib/Template/Caribou/Tags/HTML.pm
    version: v0.2.2
  Template::Caribou::Tags::HTML::Extended:
    file: lib/Template/Caribou/Tags/HTML/Extended.pm
    version: v0.2.2
  Template::Caribou::Utils:
    file: lib/Template/Caribou/Utils.pm
    version: v0.2.2
requires:
  CSS::LESSp: 0
  Carp: 0
  List::Pairwise: 0
  Method::Signatures: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
  MooseX::Role::Parameterized: 0
  MooseX::SemiAffordanceAccessor: 0
  Path::Class: 0
  Sub::Exporter: 0
  Text::MultiMarkdown: 0
  Tie::Handle: 0
  XML::Twig: 0
  overload: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Caribou
  homepage: http://search.cpan.org/dist/Template-Caribou/
  repository: https://github.com/yanick/Template-Caribou.git
version: 0.2.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
